version: "3.9"

services:
  web:
    image: ghcr.io/olegator92/iuca-reports-web/web:dev
    container_name: iuca-reports-web-dev
    ports:
      - "1101:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    restart: unless-stopped