export const ROUTES = {
    HOME: '/',
    DASHBOARD: '/dashboard',
    DEPARTMENTS: '/departments',
    POSITIONS: '/positions',
    TEMPLATES: '/templates',
    TEMPLATE_EDIT: '/templates/:id/edit',
    ROLES: '/roles',
    USERS: '/users',
    DAILY_NOTES: '/daily-notes',
    DAILY_REPORTS: '/daily-reports',
    WEEKLY_REPORTS: '/weekly-reports',
    SUPERVISOR_REPORTS: '/supervisor-reports',
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_EMAIL: '/verify-email',
    PROFILE: '/profile',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    FORBIDDEN: '/forbidden',
    PRIVACY_POLICY: '/privacy-policy',
    TERMS_OF_USE: '/terms-of-use'
}
